FROM metabase/metabase:latest

ENV MB_DB_TYPE=h2
ENV MB_DB_FILE=/metabase-data/metabase.db

# Create plugins directory if it doesn't exist
RUN mkdir -p /plugins

# Copy the DuckDB driver from the local drivers directory to the default plugins directory
COPY drivers/duckdb.metabase-driver.jar /plugins/
